more temurin attempt

diff --git a/src/Dockerfile-temurin b/src/Dockerfile-temurin
--- a/src/Dockerfile-temurin
+++ b/src/Dockerfile-temurin
@@ -8,23 +8,31 @@ RUN <<EOT
 set -eux
 export DEBIAN_FRONTEND="noninteractive"
 
-# hopefully this fixes the random connection error issue
-# https://github.com/adoptium/installer/issues/766#issuecomment-1856884963
-cat <<EOF > /etc/apt/apt.conf.d/timeout_tweak.conf
-Acquire::http::Timeout "30";
-Acquire::http::ConnectionAttemptDelayMsec "2000";
-Acquire::https::Timeout "30";
-Acquire::https::ConnectionAttemptDelayMsec "2000";
-Acquire::ftp::Timeout "30";
-Acquire::ftp::ConnectionAttemptDelayMsec "2000";
-Acquire::Retries "15";
-EOF
-
 apt-get update
 apt-get install -y gnupg ca-certificates curl apt-transport-https
-curl -so- https://packages.adoptium.net/artifactory/api/gpg/key/public | gpg --dearmor -o /etc/apt/trusted.gpg.d/adoptium.gpg
-echo "deb https://packages.adoptium.net/artifactory/deb $(awk -F= '/^VERSION_CODENAME/{print$2}' /etc/os-release) main" | tee /etc/apt/sources.list.d/adoptium.list
+curl -so- https://packages.adoptium.net/artifactory/api/gpg/key/public | tee /etc/apt/keyrings/adoptium.asc
+echo "deb [signed-by=/etc/apt/keyrings/adoptium.asc] https://packages.adoptium.net/artifactory/deb $(awk -F= '/^VERSION_CODENAME/{print$2}' /etc/os-release) main" | tee /etc/apt/sources.list.d/adoptium.list
 apt-get update
-apt-get install -y "temurin-${JAVA}-jdk"
-rm -rf /var/lib/apt/lists/* /etc/apt/apt.conf.d/timeout_tweak.conf
+
+# The temurin source is currently very unstable, add more retries for it
+# https://github.com/adoptium/adoptium-support/issues/554
+# https://github.com/adoptium/installer/issues/766
+set +e
+attempts=5
+for attempt in $(seq 1 $attempts); do
+  if apt-get install -y "temurin-${JAVA}-jdk"; then
+    break
+  fi
+  if [ "$attempt" != "$attempts" ]; then
+    echo "Install attempt #$attempt failed. Waiting 30 seconds for another attempt..."
+    sleep 30
+    update-ca-certificates
+  else
+    echo "All $attempts attempts failed"
+    exit 1
+  fi
+done
+set -e
+
+rm -rf /var/lib/apt/lists/*
 EOT
